# Generated by Django 3.2.4 on 2024-01-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_chapterpdf_chaptervideo_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChapterPDF',
            new_name='CoursePDF',
        ),
        migrations.RenameModel(
            old_name='ChapterVideo',
            new_name='CourseVideo',
        ),
        migrations.RenameField(
            model_name='coursepdf',
            old_name='chapter',
            new_name='courseP',
        ),
        migrations.RenameField(
            model_name='coursevideo',
            old_name='chapter',
            new_name='courseV',
        ),
    ]
